#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/techpack/sec-display/msm -I$(srctree)/techpack/sec-display/msm/dsi -I$(srctree)/techpack/sec-display/msm/sde -I$(srctree)/techpack/sec-display/msm/samsung

obj-y  += ss_dsi_panel_ANA38401_AMSA05RB06.o
obj-y  += ss_dsi_smart_dimming_ANA38401_AMSA05RB06.o
obj-y  += ss_dsi_interpolation_ANA38401_AMSA05RB06.o
