# SPDX-License-Identifier: GPL-2.0-only
TECHPACK?=y

techpack-dirs := $(shell find $(srctree)/techpack -maxdepth 1 -mindepth 1 -type d -not -name ".*" -not -name "*camera" -not -name "*display")
ifeq ($(CONFIG_TECHPACK_CAMERA_SAMSUNG),y)
techpack-dirs += $(srctree)/techpack/sec-camera
else
techpack-dirs += $(srctree)/techpack/camera
endif
ifeq ($(CONFIG_TECHPACK_DISPLAY_SAMSUNG),y)
techpack-dirs += $(srctree)/techpack/sec-display
else
techpack-dirs += $(srctree)/techpack/display
endif
obj-${TECHPACK} += stub/ $(addsuffix /,$(subst $(srctree)/techpack/,,$(techpack-dirs)))

techpack-header-dirs := $(shell find $(srctree)/techpack -maxdepth 1 -mindepth 1 -type d -not -name ".*" -not -name "*camera" -not -name "*display")
ifeq ($(CONFIG_TECHPACK_CAMERA_SAMSUNG),y)
techpack-header-dirs += $(srctree)/techpack/sec-camera
else
techpack-header-dirs += $(srctree)/techpack/camera
endif
ifeq ($(CONFIG_TECHPACK_DISPLAY_SAMSUNG),y)
techpack-header-dirs += $(srctree)/techpack/sec-display
else
techpack-header-dirs += $(srctree)/techpack/display
endif

header-${TECHPACK} += $(addsuffix /include/uapi/,$(subst $(srctree)/techpack/,,$(techpack-header-dirs)))